### ISSUE TITLE
[Feature] (potentially) Closures to set field value using model

### ISSUE THREAD

**Issue by theshaunwalker** [kristijanhusak/laravel-form-builder#109] opened 2015-06-08 12:16 UTC
I'm looking into this atm but figured I'd post an issue to see any thoughts.

My models have mutators that return objects (including a `__toString()` but that doesnt seem to help), so binding the actual value I need to display in a field doesnt seem to happen, presumably because `$model->field_value` returns an object which Laravels form binding cant do anything with.

The solution I have in mind is ability to pass an option to the field, which contains a closure on how to resolve what to display, something like:
```php
[
  'model_value' => function($modelField){
     return $modelField->getActualValue();
  }
]
```

So at somepoint we check if we're model binding, and the field we're rendering at the moment has a `'model_value'` option, it uses that instead of straight model binding.

Any thoughts?

EDIT:
Plain laravel form model binding utilises the `__toString()` so it does work, somewhere in the package its just switching to the default value.

**Comment by theshaunwalker** [comment] 2015-06-08 12:33
Found the issue, a fields `'default_value'` is passed to laravel's form functions, which is overriding form model binding apparently.

Working on a PR

**Comment by theshaunwalker** [comment] 2015-06-08 12:51
Re-opening as need input.

I have a fix in mind, but I need to check, is there a reason the default value of the `Form`'s `$model` is an empty array? When logically it should either have 1 model or be null?

**Comment by kristijanhusak** [comment] 2015-06-08 13:39
Form model binding is not done by Laravel's Form builder any more, i removed that in version 1.5. It is done manually, by setting values to `default_value` property, and sending it to view. You can use a Closure to modify the value for the field, check [here](http://kristijanhusak.github.io/laravel-form-builder/field/basic-input-types.html).

**Comment by theshaunwalker** [comment] 2015-06-08 13:42
Yeah I literally just discovered that closures are actually implemented xD 

I still have a PR to make though as the current behavior is if a "default_value" is passed in a fields options, then that overrides the model value, which is wrong imo. "default_value" should only be used in a case where none other is provided.

So making a PR to fix that if you agree?

**Comment by kristijanhusak** [comment] 2015-06-08 13:55
At point when i started working on the package i wanted it to be similar to symfony's form component as much as possible. For some reason I thought that there is an option `default_value` which is used to basically hardcode the value for the field. It is basically [data](http://symfony.com/doc/current/reference/forms/types/form.html#data). 
When it is typed in, it's used every time, if not, data from model is used. 
So it works as intended, but naming is fucked up. I'll probably rename it it in the next minor version to `data` or `value`, not sure which one is better.

**Comment by theshaunwalker** [comment] 2015-06-08 13:57
Yeah was gonna say having a `value` option as a method of still forcing the value is probably best included, I'm making the code changes regardless for what I need so I'll make a PR when I'm done with added `value` option and handling `default_value` like a default.

**Comment by theshaunwalker** [comment] 2015-06-08 14:15
To limit BC breaking changes, I'm thinking of sticking with `'default_value'` as the holder of the value for the field, but introduce `'value'` to the options so from now on, when you want to set a fallback when no value is set for a field, `'default_value'` is what you pass, and when you want to explicitly set a value for the field yourself `'value'` is passed.
This keeps everything in the views and passed the `FormField` constructor the same.

**Comment by kristijanhusak** [comment] 2015-06-08 14:53
I'm planning to release 1.6 version, and i believe changing `default_value` to something else is acceptable. I would change `default_value` to `value`, and this "fallback" value to `default_value`. What do you think?

**Comment by theshaunwalker** [comment] 2015-06-08 14:55
I would agree to keep naming consistant throughout, currently wrestling with my changes breaking things elsewhere :P

**Comment by kristijanhusak** [comment] 2015-06-11 20:49
This is done in https://github.com/kristijanhusak/laravel-form-builder/pull/112 . Closing.

**Closed by kristijanhusak** 2015-06-11 20:49 UTC
