### ISSUE TITLE
1.12 - Issue upgrading running `php artisan optimize`

### ISSUE THREAD

**Issue by njbarrett** [kristijanhusak/laravel-form-builder#354] opened 2017-05-29 05:38 UTC
There seems to be an issue with the 1.12 version update.
Upon upgrading today I get this error when composer runs `php artisan optimize`

```
PHP Fatal error:  Uncaught ErrorException: class_uses(): Class local does not exist and could not be loaded in /Users/nick/Sites/xx/vendor/kris/laravel-form-builder/src/Kris/LaravelFormBuilder/FormBuilderServiceProvider.php:44
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'class_uses(): C...', '/Users/nick/Sit...', 44, Array)
#1 /Users/nick/Sites/xx/vendor/kris/laravel-form-builder/src/Kris/LaravelFormBuilder/FormBuilderServiceProvider.php(44): class_uses('local')
#2 /Users/nick/Sites/xx/vendor/laravel/framework/src/Illuminate/Container/Container.php(1011): Kris\LaravelFormBuilder\FormBuilderServiceProvider->Kris\LaravelFormBuilder\{closure}('local', Object(Illuminate\Foundation\Application))
#3 /Users/nick/Sites/xx/vendor/laravel/framework/src/Illuminate/Container/Container.php(954): Illuminate\Container\Container->fireCallbackArray('local', Array)
#4 /Users/nick/Sites/xx/vendor/laravel/framework/src/Illuminate/Container/Container.php(6 in /Users/nick/Sites/xx/vendor/kris/laravel-form-builder/src/Kris/LaravelFormBuilder/FormBuilderServiceProvider.php on line 44
```

**Comment by kristijanhusak** [comment] 2017-05-29 07:11
@njbarrett unfortunately i cannot reproduce. Do you have any class that is named `local`, or any alias in the container with that name?
I would ask you to test one thing and tell me if it works. Open This file:
```
vendor/kris/laravel-form-builder/src/Kris/LaravelFormBuilder/FormBuilderServiceProvider.php
```

And on line 44 add a `false` parameter to `class_uses`.
So currently that like looks like this:
```php
if (in_array(ValidatesWhenResolved::class, class_uses($object)) && $request->method() !== 'GET') {

```

And after changing like this:
```php
if (in_array(ValidatesWhenResolved::class, class_uses($object, false)) && $request->method() !== 'GET') {

```
Please let me know if that worked out.

**Comment by veneliniliev** [comment] 2017-05-29 07:25
same error for me when add this line...

**Comment by kristijanhusak** [comment] 2017-05-29 07:27
@veneliniliev @njbarrett what exact laravel version you are using?

**Comment by veneliniliev** [comment] 2017-05-29 07:28
"laravel/framework": "5.3.*",

**Comment by njbarrett** [comment] 2017-05-29 07:28
```
            "name": "laravel/framework",
            "version": "v5.4.23",
```

**Comment by njbarrett** [comment] 2017-05-29 07:32
@kristijanhusak I also get the same error with that line modification. I am on PHP 7.0.19

**Comment by kristijanhusak** [comment] 2017-05-29 07:59
I just tested on v5.3.31 and v5.4.23, and cannot reproduce. I tested on fresh applications.
Did you guys update your apps from some older version? Do you have anything named `local` in your folder structure?
can you also try replacing `$this->app->resolving` with `$this->app->afterResolving` on line 41?

**Comment by veneliniliev** [comment] 2017-05-29 08:08
not working with afterResolving... return same error
```
ErrorException in FormBuilderServiceProvider.php line 44:
class_uses(): Class local does not exist and could not be loaded
```
tested on laravel/framework  v5.3.31
i dont have `local` folder or anything file...

**Comment by eightyfive** [comment] 2017-05-29 08:14
I'm facing the same issue.

```
"laravel/framework": "5.4.*",
"kris/laravel-form-builder": "^1.12"
```

**Comment by kristijanhusak** [comment] 2017-05-29 08:14
@veneliniliev sorry for bothering you, but i need only one more thing tested.
Replace line 41 with this:
```php
$this->app->afterResolving(\Kris\LaravelFormBuilder\Form::class, function ($object, $app) {
```
And see what happens.

**Comment by eightyfive** [comment] 2017-05-29 08:15
@kristijanhusak that seems to resolve the issue for me (no more exception)

**Closed** 2017-05-29 08:16 UTC

**Comment by veneliniliev** [comment] 2017-05-29 08:17
yes... it's working! tnx bro :)

**Comment by kristijanhusak** [comment] 2017-05-29 08:18
I just releases version 1.12.1 with the fix. Sorry for the inconvenience.

**Comment by njbarrett** [comment] 2017-05-29 09:13
This fixed the issue, thanks.
